/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md.
 *
 **********************************************************************
 * BlockHasher: independent block-hash recomputation, conformance-locked.
 *
 * The committed test/fixtures/block-hash-vectors.json was generated by running
 * BlockHasher's assembly through the REAL xchain-indexer getDataHash (see
 * gen-block-hash-vectors.js). This suite replays the same canned replica rows
 * through BlockHasher + sync's own Utility.getDataHash and asserts the hashes
 * match, locking sync's recompute (assembly + serialization) to the indexer's
 * canon with no runtime cross-repo dependency. The xchain-e2e-test recompute
 * scenario is the live cross-repo drift guard.
 ********************************************************************/

const assert  = require('assert');
const path    = require('path');
const BlockHasher = require('../../src/BlockHasher');
const Utility = require('../../src/utility');
const vectors = require('../fixtures/block-hash-vectors.json');

// A BlockHasher whose db.doQuery returns the canned result-sets in CALL ORDER.
function hasherFor(results){
    let i = 0;
    const db = { doQuery: async () => results[i++] };
    return new BlockHasher(db, new Utility());
}

describe('BlockHasher: independent recompute conformance @regression', function(){

    it('reproduces the indexer-authentic committed hashes from canned replica rows', async function(){
        const got = await hasherFor(vectors.results.map(r => r.slice())).computeBlockHashes(vectors.block_index);
        assert.deepStrictEqual(got, vectors.expected,
            'sync BlockHasher must reproduce the indexer getDataHash output byte-for-byte');
    });

    it('RED: tampering a single replicated row changes the recomputed hash', async function(){
        // Alter one credit amount (the smallest possible data tamper).
        const tampered = vectors.results.map(r => r.map(row => Object.assign({}, row)));
        tampered[0][0].amount = String(Number(tampered[0][0].amount) + 1);
        const got = await hasherFor(tampered).computeBlockHashes(vectors.block_index);
        assert.notStrictEqual(got.ledger_hash, vectors.expected.ledger_hash,
            'a tampered credit row MUST change the ledger hash (else corruption is invisible)');
        // actions/contract hashes are unaffected by a credit-only change.
        assert.strictEqual(got.actions_hash, vectors.expected.actions_hash);
        assert.strictEqual(got.contract_hash, vectors.expected.contract_hash);
    });

    it('reordering rows changes the hash (ORDER BY is consensus-significant)', async function(){
        const reordered = vectors.results.map(r => r.slice());
        reordered[3] = [reordered[3][1], reordered[3][0], reordered[3][2]]; // swap two actions
        const got = await hasherFor(reordered).computeBlockHashes(vectors.block_index);
        assert.notStrictEqual(got.actions_hash, vectors.expected.actions_hash);
    });

    it('an all-empty block with no previous hash recomputes without error', async function(){
        const empty = [[],[],[],[],[],[],[],[],[],[],[]]; // 11 empty result-sets (no prev-hash row)
        const got = await hasherFor(empty).computeBlockHashes(1);
        assert.ok(got.ledger_hash && got.actions_hash && got.contract_hash,
            'empty block still yields the three chained hashes');
    });
});
