/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md.
 *
 **********************************************************************
 * BlockHasher: independent block-hash recomputation, conformance-locked.
 *
 * The committed test/fixtures/block-hash-vectors.json was generated by running
 * sync's own BlockHasher assembly through the xchain-indexer getDataHash
 * serializer (see gen-block-hash-vectors.js). This suite replays the same canned
 * replica rows through BlockHasher + sync's own Utility.getDataHash and asserts
 * the hashes match: a self-regression lock on sync's recompute, not proof of
 * parity with the indexer. Cross-repo parity is guarded by
 * blockhash_conformance_twin.test.js and the xchain-e2e-test recompute scenario.
 ********************************************************************/

const assert  = require('assert');
const path    = require('path');
const BlockHasher = require('../../src/client/block_hasher');
const Utility = require('../../src/util');
const { makeTestDatabase } = require('./support/fake_db');
const vectors = require('../fixtures/block-hash-vectors.json');

// A BlockHasher whose strict reader returns the canned result-sets in CALL ORDER.
// The fail-soft reader throws, so a gather that regresses to doQuery fails here.
function hasherFor(results){
    let i = 0;
    const db = {
        doQuery: async () => { throw new Error('fail-soft doQuery used for a consensus preimage gather'); },
        doQueryStrict: async () => results[i++]
    };
    return new BlockHasher(db, new Utility());
}

describe('BlockHasher: independent recompute conformance @regression', function(){

    it('reproduces the committed golden hashes from canned replica rows', async function(){
        const got = await hasherFor(vectors.results.map(r => r.slice())).computeBlockHashes(vectors.block_index);
        assert.deepStrictEqual(got, vectors.expected,
            'sync BlockHasher must reproduce the committed golden byte-for-byte');
    });

    it('RED: tampering a single replicated row changes the recomputed hash', async function(){
        // Alter one credit amount (the smallest possible data tamper).
        const tampered = vectors.results.map(r => r.map(row => Object.assign({}, row)));
        tampered[0][0].amount = String(Number(tampered[0][0].amount) + 1);
        const got = await hasherFor(tampered).computeBlockHashes(vectors.block_index);
        assert.notStrictEqual(got.ledger_hash, vectors.expected.ledger_hash,
            'a tampered credit row MUST change the ledger hash (else corruption is invisible)');
        // actions/contract hashes are unaffected by a credit-only change.
        assert.strictEqual(got.actions_hash, vectors.expected.actions_hash);
        assert.strictEqual(got.contract_hash, vectors.expected.contract_hash);
    });

    it('reordering rows changes the hash (ORDER BY is consensus-significant)', async function(){
        const reordered = vectors.results.map(r => r.slice());
        reordered[3] = [reordered[3][1], reordered[3][0], reordered[3][2]]; // swap two actions
        const got = await hasherFor(reordered).computeBlockHashes(vectors.block_index);
        assert.notStrictEqual(got.actions_hash, vectors.expected.actions_hash);
    });

    it('an all-empty block with no previous hash recomputes without error', async function(){
        const empty = [[],[],[],[],[],[],[],[],[],[],[]]; // 11 empty result-sets (no prev-hash row)
        const got = await hasherFor(empty).computeBlockHashes(1);
        assert.ok(got.ledger_hash && got.actions_hash && got.contract_hash,
            'empty block still yields the three chained hashes');
    });

    it('a read error rejects instead of hashing a truncated preimage', async function(){
        // Model the production reader: doQuery swallows the error into [], doQueryStrict throws.
        let call = 0;
        const db = {
            doQuery: async () => [],
            doQueryStrict: async () => {
                if(++call === 3) throw new Error('lock wait timeout on escrows');
                return [];
            }
        };
        await assert.rejects(new BlockHasher(db, new Utility()).computeBlockHashes(vectors.block_index),
            /lock wait timeout on escrows/,
            'a failed gather must surface as a recompute error, never as an empty row set');
    });
});

// Capture emitted SQL while feeding empty result-sets.
function capturingHasher(calls){
    const capture = async (sql) => { calls.push(sql); return []; };
    const db = { doQuery: capture, doQueryStrict: capture };
    return new BlockHasher(db, new Utility());
}
const stateQueryOf = (calls) => {
    const hit = calls.find(q => /FROM contract_state cs/.test(q));
    assert.ok(hit, 'contract-state gather query not emitted');
    return hit.replace(/\s+/g, ' ');
};

describe('BlockHasher: independent recompute conformance @regression', function(){
    // state_key collation flag-day (state_key_collation_activation.js twin):
    // the contract-state gather must pin COLLATE utf8_bin exactly when the gate
    // is active, byte-for-byte with the indexer's getBlockHashes, or the
    // recompute halts diverge from the source at/after an armed height.
    describe('state_key collation gate (contract-state gather SQL)', function(){

        it('legacy folding collation when network/coin are omitted (pre-activation callers)', async function(){
            const calls = [];
            await capturingHasher(calls).computeBlockHashes(1);
            assert.doesNotMatch(stateQueryOf(calls), /COLLATE utf8_bin/);
        });

        it('legacy folding collation on an unarmed chain (mainnet placeholder)', async function(){
            const calls = [];
            await capturingHasher(calls).computeBlockHashes(900000, 'mainnet', 'BTC');
            assert.doesNotMatch(stateQueryOf(calls), /COLLATE utf8_bin/);
        });

        it('pins COLLATE utf8_bin in GROUP BY and ORDER BY on regtest (armed from genesis)', async function(){
            const calls = [];
            await capturingHasher(calls).computeBlockHashes(1, 'regtest', 'BTC');
            const q = stateQueryOf(calls);
            assert.match(q, /GROUP BY contract_index, state_key COLLATE utf8_bin/);
            assert.match(q, /ORDER BY cs\.contract_index ASC, cs\.state_key COLLATE utf8_bin ASC/);
        });
    });
});

// Capture the SQL getBlockLeafRows emits, the third copy of this gather.
async function leafRowsCalls(block_index, network, coin){
    const calls = [];
    const db = makeTestDatabase('idx', 'u', 'p', { isNull: x => x == null }, 'indexer');
    const capture = async (sql) => { calls.push(sql); return []; };
    db.doQuery = capture;
    db.doQueryStrict = capture;
    await db.getBlockLeafRows(block_index, undefined, network, coin);
    return calls;
}

describe('BlockHasher: contract_state gather parity with getBlockLeafRows @regression', function(){
    // A one-sided gate or splice edit forks block_merkle_root against the recompute.
    for(const [label, args, armed] of [['armed (regtest)', [1, 'regtest', 'BTC'], true],
                                       ['unarmed (mainnet placeholder)', [900000, 'mainnet', 'BTC'], false],
                                       ['no network/coin', [1], false]]){
        it('getBlockLeafRows emits the same contract_state SQL as BlockHasher, ' + label, async function(){
            const hashCalls = [];
            await capturingHasher(hashCalls).computeBlockHashes(...args);
            const leafQ = stateQueryOf(await leafRowsCalls(...args));
            const hashQ = stateQueryOf(hashCalls);
            assert.strictEqual(leafQ.trim(), hashQ.trim(),
                'db.getBlockLeafRows and BlockHasher.computeBlockHashes emit different contract_state SQL');
            const collated = (hashQ.match(/state_key COLLATE utf8_bin/g) || []).length;
            assert.strictEqual(collated, armed ? 2 : 0,
                'expected COLLATE utf8_bin on ' + (armed ? 'both' : 'neither') + ' state_key uses, got ' + collated);
        });
    }
});

// Recompute the golden block with one ledger row's address replaced (escrows is
// empty in the golden, so that slot gets one pushed row instead).
const { ROLE_BY_ADDRESS } = require('../../src/util/protocol_address_roles');
async function hashWithLedgerAddress(slot, address){
    const fresh = vectors.results.map(r => r.map(row => Object.assign({}, row)));
    if(fresh[slot].length) fresh[slot][0].address = address;
    else fresh[slot].push({ action_index: 1, address: address, tick: 'JDOG', amount: '1' });
    return hasherFor(fresh).computeBlockHashes(vectors.block_index);
}

describe('BlockHasher: special-address canonicalization reaches the preimage @regression', function(){
    // A per-chain special address must hash as its chain-independent role token,
    // or the follower forks from the indexer on the first DONATE/BURN block.
    const BTC_DONATE1 = '1Donate1GERVKPW6GFQcnGeTa8dgL6Abyp', LTC_DONATE1 = 'Ldonate18tNZcVThKm5MX33EjvhaanJ6Mg';

    it('the DONATE1 role map still names both chain addresses this suite uses', function(){
        assert.strictEqual(ROLE_BY_ADDRESS[BTC_DONATE1], 'DONATE1');
        assert.strictEqual(ROLE_BY_ADDRESS[LTC_DONATE1], 'DONATE1');
    });

    for(const [label, slot] of [['credits', 0], ['debits', 1], ['escrows', 2]]){
        it('the ' + label + ' slot hashes BTC DONATE1, LTC DONATE1 and the role token identically', async function(){
            const btc   = await hashWithLedgerAddress(slot, BTC_DONATE1);
            const ltc   = await hashWithLedgerAddress(slot, LTC_DONATE1);
            const token = await hashWithLedgerAddress(slot, 'DONATE1');
            const plain = await hashWithLedgerAddress(slot, '1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev');
            assert.strictEqual(btc.ledger_hash, token.ledger_hash,
                'BlockHasher must hash a BTC DONATE1 ' + label + ' row as the DONATE1 role token');
            assert.strictEqual(ltc.ledger_hash, token.ledger_hash,
                'BlockHasher must hash an LTC DONATE1 ' + label + ' row as the DONATE1 role token');
            assert.notStrictEqual(plain.ledger_hash, token.ledger_hash,
                'a plain address must not hash like the role token (the substitution would be vacuous)');
            for(const got of [btc, ltc, token, plain]){
                assert.strictEqual(got.actions_hash, vectors.expected.actions_hash);
                assert.strictEqual(got.contract_hash, vectors.expected.contract_hash);
            }
        });
    }
});

// Every gather resolves its call-site template to a BLOCK_HASH_QUERIES entry. A one-sided
// edit of either copy makes consensusSql throw, so this case goes red instead of the
// recompute hashing an empty row set for that table.
describe('BlockHasher: every gather resolves a non-empty SQL @regression', function(){
    for(const [label, args] of [['no network/coin', [1]],
                                ['unarmed (mainnet placeholder)', [900000, 'mainnet', 'BTC']],
                                ['armed (regtest)', [1, 'regtest', 'BTC']]]){
        it('issues 11 resolved queries, ' + label, async function(){
            const calls = [];
            await capturingHasher(calls).computeBlockHashes(...args);
            assert.strictEqual(calls.length, 11, 'ten preimage gathers plus the previous-hash read');
            for(const q of calls)
                assert.ok(typeof q === 'string' && q.trim().length > 0, 'unresolved gather SQL: ' + q);
        });
    }
});
