/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md.
 *
 **********************************************************************
 * state_hash — replication-integrity hash conformance, golden-locked.
 *
 * test/fixtures/state-hash-vectors.json was generated by running the shared
 * buildStateHashData over canned RESOLVED rows and hashing with the REAL
 * xchain-indexer getDataHash (see gen-state-hash-vectors.js). This suite replays
 * the same canned rows through buildStateHashData + sync's own Utility.getDataHash
 * and asserts the hash matches — locking sync's state_hash assembly + serialization
 * to the indexer's canon with no runtime cross-repo dependency. The xchain-e2e-test
 * recompute scenario is the live cross-repo drift guard.
 ********************************************************************/

const assert  = require('assert');
const { buildStateHashData, STATE_HASH_VERSION } = require('../../src/stateHash');
const Utility = require('../../src/utility');
const vectors = require('../fixtures/state-hash-vectors.json');

// A db whose doQuery returns the canned result-sets in CALL ORDER, plus a fixed
// completed status id (buildStateHashData calls getStatusId once, up front).
function dbFor(results, completedId){
    let i = 0;
    return {
        doQuery:     async () => results[i++],
        getStatusId: async () => completedId
    };
}

async function hashWith(db){
    const data = await buildStateHashData(db, vectors.block_index, {
        activationDelay: vectors.activation_delay,
        gasTick:         vectors.gas_tick
    });
    return { data, hash: new Utility().getDataHash(data) };
}

describe('state_hash — replication-integrity recompute conformance @regression', function(){

    it('reproduces the indexer-authentic committed state_hash from canned resolved rows', async function(){
        const { hash } = await hashWith(dbFor(vectors.results.map(r => r.slice()), vectors.completed_id));
        assert.strictEqual(hash, vectors.expected_state_hash,
            'sync buildStateHashData + getDataHash must reproduce the indexer getDataHash output byte-for-byte');
    });

    it('builds the fixed-order preimage covering every mutation class', async function(){
        const { data } = await hashWith(dbFor(vectors.results.map(r => r.slice()), vectors.completed_id));
        assert.deepStrictEqual(Object.keys(data),
            ['deactivations', 'slashes', 'request_status', 'cooldown', 'credits', 'block_index', 'state_hash_version'],
            'preimage key order is part of the hash — must not change without a STATE_HASH_VERSION bump');
        assert.strictEqual(data.state_hash_version, STATE_HASH_VERSION);
        assert.strictEqual(data.block_index, vectors.block_index);
        // id-resolution: the cooldown class carries the resolved status STRING, never status_id.
        assert.strictEqual(data.cooldown.unstakes[0].status, 'completed');
        // credits carry resolved address/tick strings.
        assert.strictEqual(typeof data.credits[0].address, 'string');
        assert.strictEqual(typeof data.credits[0].tick, 'string');
    });

    it('RED: tampering any single mutated row changes the state_hash', async function(){
        // Flip one cooldown status (index 10 = cooldown.unstakes result-set) — the smallest tamper.
        const tampered = vectors.results.map(r => r.map(row => Object.assign({}, row)));
        tampered[10][0].status = 'pending';
        const { hash } = await hashWith(dbFor(tampered, vectors.completed_id));
        assert.notStrictEqual(hash, vectors.expected_state_hash,
            'a tampered cooldown-status row MUST change the state_hash (else the divergence is invisible)');
    });

    it('RED: a missing backdated credit (dropped apply) changes the state_hash', async function(){
        const dropped = vectors.results.map(r => r.map(row => Object.assign({}, row)));
        dropped[12] = [dropped[12][0]];   // drop the second refund credit
        const { hash } = await hashWith(dbFor(dropped, vectors.completed_id));
        assert.notStrictEqual(hash, vectors.expected_state_hash,
            'a follower missing a refund credit MUST recompute a different state_hash and halt');
    });
});
